# Use root/example as user/password credentials
version: '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:                                  # 환경 변수
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=tkdgyu
      - MYSQL_PASSWORD=g661027
      - MYSQL_ROOT_PASSWORD=g661027
      - TZ=Asia/Seoul